version: "3.9"

services:
  service-db:
    image: "postgres:13.2"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: transaction-bug
      POSTGRES_PASSWORD: mysecretpassword

  service:
    platform: linux/amd64

    build:
      context: .
      dockerfile: ./docker/Dockerfile

    ports:
      - 8000:8000

    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@service-db:5432/transaction-bug
